name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Organização Nomaryth Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nomaryth
          base: header, activity, community, repositories, metadata
          filename: github-metrics-nomaryth.svg
          output_action: commit
          plugin_languages: yes
          plugin_languages_sections: most-used
          config_timezone: America/Sao_Paulo
          theme: transparent
          
      - name: Organização Axulogic Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Axulogic
          base: header, activity, community, repositories, metadata
          filename: github-metrics-axulogic.svg
          output_action: commit
          plugin_languages: yes
          plugin_languages_sections: most-used
          config_timezone: America/Sao_Paulo
          theme: transparent
