name: update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🎏 Fetch repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: ✨ Create ReadMe.md
        run: |
          cd ${GITHUB_WORKSPACE}/
          npm i
          node src/update.js
      - name: 🚀 Deploy
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin https://$PAT_TOKEN@github.com/${{ github.repository }}.git

          # Verifica se houve alterações antes de adicionar
          git diff --exit-code || (
            git add . &&
            git commit -am "[Automatic] Updated ReadMe.md" &&
            git push origin main
          )